### ISSUE TITLE
Make atom ids available (and alterable) in biopython.structure

### ISSUE THREAD

**Issue by danijoo** [padix-key/biopython2#3]
Sometimes it is neccessary to access and/or alter the atom ids in a pdb file. Right now this is not possible because atom ids are not stored when reading from pdb files and are assigned starting from 1when writing pdb files.

Imaging the following case: I want to read a protein structure from PDB and only save its CA atoms to a new file, but without altering their atom ids. Right now atom ids are reassigned starting from 1 and there is no way to alter this.

Possible implementation would be to add another field to ```biopython.structure.Atom``` which is initialized from the PDB file. ```biopython.structure.io.pdb.PDBFile#write``` could then allow to renumber atom ids or reuse the old ones:

```python
pdb_file.set_structure(stack)
pdb_file.write("1l2y.pdb", renumber=True) # writes atom ids starting from 1 (current default)
pdb_file.write("1l2y.pdb") # keeps atom ids of the AtomArray
```

**Comment by padix-key** [comment]
Fixed by 667312473c2a00f409481285ec63e49952060073
PDB and PDBx files have now full support of optional annotation arrays. In this particular case you can either load the structure from file with `extra_fields=["atom_id"]`, which creates the `atom_id` annotation array from file, or you can set `atom_id` afterwards. When writing the loaded atom array or stack into a PDB or PDBx file, the `atom_id` annotation is automatically recognized and used instead of continuous numbering.
